version: '2'
services:
  elastic:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    networks:
      - elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:7.17.0
    networks:
      - elastic
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
networks:
  elastic: {}
